name:           Terence's Blog
description:    "Jugglers and singers require applause"

permalink:      /:title.html
markdown:       GFM
highlighter:	rouge
logo:           false

url:            "http://songtl.github.com"
author:         "Terence.Song"
bio:            "Jugglers and singers require applause"

github:         songtl
