name:           Terence's Blog
description:    "Jugglers and singers require applause"

permalink:      /:title.html
markdown:       redcarpet
highlighter:	pygments
logo:           false

url:            "http://songtl.github.cc"
author:         "Terence.Song"
bio:            "Jugglers and singers require applause"

github:         songtl
