name:           Terence's Blog
description:    "Jugglers and singers require applause"

markdown:       redcarpet
highlighter:	pygments
logo:           false

url:            "http://songtl.github.com"
author:         "Terence.Song"
bio:            "Jugglers and singers require applause"

github:         songtl
